stages:
  - build
  - deploy

before_script:
  - TAGGER_ROOT=${VAR_TAGGER_ROOT:-/opt/tagger}
  - ENV_ROOT=${VAR_ENV_ROOT:-/opt/env}
  - PROJECT=${VAR_PROJECT_NAME:-$CI_PROJECT_NAME}
  - TAG=${CI_COMMIT_REF_SLUG}

build image:
  stage: build
  script:
    - CONSUL_TEMPLATE_ETC=${VAR_CONSUL_TEMPLATE_ETC:-/opt/etc/consul-template}
    - sed -i
      -e "s/{PROJECT}/${PROJECT}/g"
      -e "s/{TAG}/${TAG}/g"
      .env.tpl
    - ${TAGGER_ROOT}/template/laravel-env.sh
      -c ${CONSUL_TEMPLATE_ETC}
      -e ${ENV_ROOT}
      -s ${PWD}/.env.tpl
      -p ${PROJECT}
      -t ${TAG}
    - composer install
      --optimize-autoloader
      --no-dev
      --no-interaction
      --no-progress
      --no-suggest
    - docker build --force-rm -t ${PROJECT}:${TAG} .

deploy master:
  stage: deploy
  script:
    - ROOT_DOMAIN=${VAR_ROOT_DOMAIN}
    - CERT_NAME=${VAR_CERT_NAME:-default}
    - ${TAGGER_ROOT}/web/run.sh
      -d ${PROJECT}.${ROOT_DOMAIN}
      -e ${ENV_ROOT}/${PROJECT}/${TAG}:/app/storage/env
      -l "--log-driver gelf --log-opt gelf-address=${GELF_ADDRESS}"
      -p ${PROJECT}
      -t ${TAG}
      -c ${CERT_NAME}
  only:
    - master

deploy tags:
  stage: deploy
  script:
    - ROOT_DOMAIN=${VAR_ROOT_DOMAIN}
    - CERT_NAME=${VAR_CERT_NAME:-default}
    - DB_SOURCE_TAG=${VAR_DB_SOURCE_TAG:-latest}
    - DB_BACKUP_ROOT=${VAR_DB_BACKUP_ROOT:-/opt/backups/mysql}
    - ${TAGGER_ROOT}/mysql/spawn.sh
      -b ${DB_BACKUP_ROOT}
      -p ${PROJECT}
      -s ${DB_SOURCE_TAG}
      -t ${TAG}
    - ${TAGGER_ROOT}/web/run.sh
      -d ${PROJECT}-${TAG}.${ROOT_DOMAIN}
      -e ${ENV_ROOT}/${PROJECT}/${TAG}:/app/storage/env
      -p ${PROJECT}
      -t ${TAG}
      -c ${CERT_NAME}
  only:
    - tags

